### ISSUE TITLE
FEAT : 노션 API를 이용한 게임데이터 수집기능 개발

### ISSUE THREAD

**Issue by bsh714-dev** [gachimind/backend#134]
**FEATURE**
노션 API를 이용한 게임데이터 수집기능 개발

**HOW**
게임데이터 수집후 노션 API를 이용해 노션페이지에 저장

**ERROR HANDLING**
_발생할 수 있는 에러 상황을 예측해보고 어떻게 핸들링할지 적어주세요._

**Comment by jn33-dev** [comment]
@bsh714-dev 

- 현재 게임이 진행 중인 전체 방 개수는 아래 count 메서드로 db에서 검색하시면 됩니다.  
- 현재 플레이어 수는 player엔티티를 count 하시면 됩니다. 
![Image](https://user-images.githubusercontent.com/102890891/215240096-bf10ca27-dc13-441b-b758-59de9eec14bc.png)

- 누적 room 수는 between옵션을 사용하셔서 createdAt 기준으로 검색하시면 될것 같습니다. 
- 누적 플레이어수는 gameResult 엔티티를 between 검색 옵션으로 count하시면 됩니다!
![Image](https://user-images.githubusercontent.com/102890891/215240807-6bb87a95-487c-4edc-a80a-6e00958e9ef7.png)
- 게임이 종료된 방은 softdeleted 되는데, 아래 메서드를 사용하시면 softdeleted 된 것 포함해서 검색해 옵니다.
![image](https://user-images.githubusercontent.com/102890891/215269855-94e7c347-6a2a-4b79-8b6f-eaa6c3d3137a.png)


- 날짜와 시간 관련해서는 zellow팀의 src/gameResult/gameResult.service.ts 파일에서 getStatBetween 메서드를 참고하시면 될것 같습니다.
![Image](https://user-images.githubusercontent.com/102890891/215240980-b43a9d39-df9f-4ab4-8c4f-1eb014883a0e.png)

**src/ 폴더 아래 statistics 폴더를 하나 만들고 거기에 statistics .controller, statistics .service 그리고 모듈 등 만들어서 검색 api 등을 만들어 주세요**

**Comment by jn33-dev** [comment]
@bsh714-dev 
세현님, 게임 로직을 수정하면서 gameResult data를 한 판이 끝나면 softdelete하는 방식으로 변경하였습니다.
누적 데이터 불러오실 때, 삭제된 room 데이터를 포함해서 불러오는 것과 같은 방식으로 gameResult 데이터도 로드 하도록 변경해주셔야 할 것 같습니다.

152번 브랜치에서 정정하였으니, 해당 브랜치 풀 받아서 작업 진행해주세요!
