### ISSUE TITLE
CHORE : [NGINX] 보안 설정 

### ISSUE THREAD

**Issue by jn33-dev** [gachimind/backend#135]
**해결해야 하는 문제 상황**
- 해킹을 시도하는 이상한 요청이 계속 옴

**Screenshots**
![image](https://user-images.githubusercontent.com/102890891/215107885-5f81b27b-3568-4d66-b46a-f58a70c5a27a.png)
![image](https://files.slack.com/files-pri/T01L2TNGW3T-F04LDRGJH1V/image.png)

**요청사항**
- nginx에서 국가별 차단 설정 / User-Agent 설정 / robots.txt 세팅
- 로그 파일 보고 해당 ip 차단 설정
   - /var/log/nginx 경로에서 access & error 로그 확인해서 찾기
- 무작위 ssh 접속 차단 설정 

참고자료
[nginx 최소 보안 설정](https://jay-ji.tistory.com/51)
[nginx 설정 예제 repo](https://gist.github.com/kmjones1979/fcabb4731bbf85b9c50189e90d76b1c1)
[nginx ssl Best Practices](https://gist.github.com/nailuoGG/8b95fc15453dd1c9d1c340646740f0cb)
[IP주소 조회](https://nordvpn.com/ko/ip-lookup/)

**Comment by pds0309** [comment]
@jn33-dev 

> 로그 파일 보고 해당 ip 차단 설정

`fail2ban`이라는 서비스를 찾아보시와요 👍

**Comment by jn33-dev** [comment]
배포 서버에는 프런트 서버 ip / 도메인으로만 접근하도록 처리하시면 될 것 같습니다

**Comment by jn33-dev** [comment]
[nginx 설정 참고 블로그](https://pamyferret.tistory.com/3)

ssl이 설정된 블록에서 해야 하며, 띄어쓰기, 괄호 갯수, ; 등이 중요했다.
```
server {

                root /var/www/html;
                server_name api.gachimind.com; # managed by Certbot

                location / {
                        if ($http_referer !~ ^(https|http)://(gachimind.com|developers.kakao.com)) {
                                return 404;
                        }
                        # First attempt to serve request as file, then
                        # as directory, then fall back to displaying a 404.
                        proxy_pass http://localhost:3000;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header Host $http_host;



                }

```
