### ISSUE TITLE
FEAT: [게임 중] 발표자 탈주시 처리

### ISSUE THREAD

**Issue by jn33-dev** [gachimind/backend#136]
**FEATURE**
- 게임 중 플레이어가 자신의 발표 턴에 탈주하는 경우 처리
- 해당 턴의 턴 정보와 timer를 삭제 -> 다음 턴을 생성하여 바로 턴 넘어가기

**HOW**
- setTimeout에 id를 부여하여 타이머 함수 종료 처리
- 발표 중 정답을 맞추 유저의 turnResult는 그대로 두기 
- 발표자의 turnResult는 0점으로 넣기
- 로직 수행 후 바로 다음 턴 정보 생성하여 클라로 정보 넘기기

**ERROR HANDLING**
**- reayTime과 speechTime에 탈주하는 경우 발생하는 상황**
   1. 탈주자가 발표자인 경우
      - 해당 턴 정보를 삭제하고 다음 턴으로 넘기면, 턴을 생성하는 현재 로직에 문제가 생김
      - 그래서, 애초에 게임 시작할 때, 전체 플레이어 수에 맞게 턴을 먼저 생성하고, gameMap을 만들어서 가지고 있다가, roomId로 player 정보 배열을 받아와서 player map에 저장한 남은 다음 사람의 turnId로 턴 정보 불러와 사용하기
      - 게임이 종료된 후 turn과 map을 초기화
      - gameMap에는 유저별 turnId, 현재 turn: number, score, rank 등의 정보 담기
   2. 탈주자가 나가고 플레이어가 1인이 되어 더이상 게임 진행이 의미가 없는 경우
      - 남은 사람이 발표자였을 경우, 100점 처리하고, 게임 종료
      - 남은 사람이 플레이어였을 경우, 게임 종료만 처리
   3. 하나의 게임 방에서 여러 판의 게임을 진행하는 경우, turnResult를 생성학 위해, 반듯이 turnId를 넣어야 식별 가능
   
 **- startCount와 discussionTime에 탈주하는 경우 발생하는 상황**
   1. startCount에서 1턴 발표자가 탈주하는 경우
      - 2번턴 발표자로 바로 넘기기
      - 만약, 방에 남은 사람이 1명이라면, 그대로 게임 종료
   2. discussionTime에 발표자가 탈주하는 경우
      - 남은 플레이어가 2명 이상이라면 카운터 계속 흐르게 두고, 발표자는 평가 받은대로 점수 반영 (아무도 평가 안하면 0점으로 반영?)
      - 남은 플레이어가 1명이라면, 그대로 게임 종료 -> 발표자 평가 점수 0으로 반영
      - **@pds0309 : 토론 시간에 나간경우, 화면에 고양이 처리는 어떻게 되나요??**

[📚 탈주범 잡자! (feat.게이밍 로직에서 데이터 사용 방법 교체)](https://summer-driver-168.notion.site/feat-728a0b512abd46128915359bf43a2c39)

**Comment by pds0309** [comment]
다 되면 바로 돌려보게습니다 👍

**Comment by pds0309** [comment]
@jn33-dev 
게임 중 나가면 고양이도 없어집니다!
