### ISSUE TITLE
FEAT : [회원] 닉네임 / 캐릭터 수정 API

### ISSUE THREAD

**Issue by jn33-dev** [gachimind/backend#151]
**FEATURE**
PATCH '/api/users/me/update'

**HOW**
- 토큰으로 파싱하여 userId 값 찾고,
- body 값으로 해당 유저의 닉네임 / 고양이 캐릭터 선택 값을 프런트에서 전달 받은 그대로 db에 저장(save)
- 성공/실패 처리는 api 명세서 참고

**ERROR HANDLING**
_발생할 수 있는 에러 상황을 예측해보고 어떻게 핸들링할지 적어주세요._

**Comment by dy-p-code** [comment]
150번 이슈와 같이 PR 날렸습니다
