### ISSUE TITLE
FEAT : [socket] update-room event로 응답할 데이터 추가

### ISSUE THREAD

**Issue by jn33-dev** [gachimind/backend#46]
**FEATURE**
- 게임 방에 변화가 생길때 방 내의 소켓에게 방 정보를 업데이트 하는 update-room event에 emit 데이터 추가

**HOW**
- 기존에` { data: room } `정보만 담던 것을 `{ data: { room, eventUserInfo }}`로 event를 발생시킨 유저의 정보 추가

**ERROR HANDLING**
- 프런트에서 더 필요한 정보가 있으면 추가 할 것
- (추가) 어떤 event가 발생했는지 정보 추가 - enter, leave, leave-force, ready, start

@pds0309

**Comment by jn33-dev** [comment]
응답값 전체 type 지정해서 관리할 것

**Comment by pds0309** [comment]
enter, leave, leave-force까지는 매우 좋은것 같습니다. 채팅창에 알려줄 수도 있고여!

게임이 시작되고 난 뒤에 발생되는 이벤트들은 엄청 복잡하고 많을 것 같아 `update-room`으로 처리 하지 않을 것으로 우선 예상이 되는데
`ready` ,`start` 상태의 경우는 모르겠네요

`ready`, `start` 부터는 고민중입니다.
 `update-room`에서 사용자의 출입 관련 로직을 많이 처리하고 있어서 
추후에 더 복잡해질까봐 걱정중입니다! ㅎㅎㅎ

`ready` `start` 부터는 게임 실행과 관련된 책임으로 보고 새로운 응답으로 `ex) [emit] ready => [on] ready`

프론트에서  `해당 방 전체` 에 `누가` `레디`or`언레디`를 했는지 정도만 얻어와도 될 것 같다는 생각이 들었습니다

생각은 많지만 솔직히 직접 해봐야 알 것 같습니다. 같이 고민해봅시다!!

프론트 쪽은 채팅은 구현이 쉽고, 홈에 브로드캐스팅되는 부분이나 방 나가기 같은 동작은 백에서 완료되면 가져다 쓰기만하면 되기때문에 rtc까지 완료된 현재 시점에서 해당 부분 개발하는데 지장이 없을 것 같네요

@jn33-dev
